#!/bin/bash
#Created by Brian Winkler
#This script is free to use and modify as your own
#Check out my blog at https://nuxview.blogspot.com/

STATUS="$(xbacklight -get)"
CHECK="${STATUS}"

if [[ $CHECK == 100.000000 ]]

then
	xbacklight -dec 9
	pkill -RTMIN+1 i3blocks

else
	xbacklight -dec 10
	pkill -RTMIN+1 i3blocks
fi
