#!/bin/bash

#Created by Brian Winkler
#Licensed under the GPL
#See more scripts at https://github.com/BrighBrigh/i3Blocks
#And check out my Linux blog at https://nuxview.blogspot.com/


#Retrieve external IP#
IP=$(wget http://ipinfo.io/ip -qO -)

#Print external IP
echo $IP
