#!/bin/bash



##Check VPN status
GET_FREEDOM=$(pgrep sshuttle)

##Store status in STATUS
if [[ $GET_FREEDOM > 0 ]]
then   
    STATUS=ON
else
    STATUS=OFF
fi



echo $STATUS
echo $STATUS



##Colors
if [[ "$STATUS" == "ON" ]]
then
    echo "#72ee7f"
else
    echo "#ee7272"
fi

